using System;

class Program
{
    // Color change function
    public static void ChangeColor(string text, bool isWin = false)
    {
        if (isWin)
        {
            Console.ForegroundColor = ConsoleColor.Green;
        }
        else 
            Console.ForegroundColor = ConsoleColor.Red;

        Console.Write(text);
        Console.ResetColor();
    }

    public static void Main(string[] args)
    {
        Random rnd = new Random();
        ConsoleColor oldColor = Console.ForegroundColor;

        Console.WriteLine("C# console number guessing game by Doruk!");
        Console.WriteLine();
        Console.WriteLine("Try to type and guess the integer generated by the computer that is between (and including) 1-99.");
        Console.WriteLine("You have to correctly guess the number in 10 trials.");
        Console.WriteLine("The computer will help you towards the correct number.");
        Console.WriteLine();

        while (true)
        {
            // Inside the game 

            Console.WriteLine("Push 'Enter' for a new game and 'Escape' to quit the game.");
            Console.WriteLine();

            // Listening for either Enter or Escape for a new game or exit command
            ConsoleKeyInfo key = Console.ReadKey(true);
            while (key.Key != ConsoleKey.Enter && key.Key != ConsoleKey.Escape)
                key = Console.ReadKey(true);

            if (key.Key == ConsoleKey.Enter)
            {
                // Started a new game

                Console.WriteLine("You started a new game.");
                Console.WriteLine("Type an integer between (and including) 1-99.");
                Console.WriteLine();

                // New integer is generated
                int correctNum = rnd.Next(1, 100);
                // Number of trials is stored
                byte trials = 0;
                // The string used for the user's bet is created.
                string betString = "";

                while (true)
                {
                    // Listening for a number input.

                    ConsoleKeyInfo currentChar = Console.ReadKey(true);

                    if (currentChar.Key == ConsoleKey.Escape)
                    {
                        // Escape button is pushed during the game

                        if (betString != "") // Go to the new line if the line is not empty
                            Console.WriteLine();

                        Console.WriteLine("Do you want to cancel the current game? 'Enter': Y / 'Escape': N");

                        ConsoleKeyInfo processKey = Console.ReadKey(true);
                        while (processKey.Key != ConsoleKey.Enter && processKey.Key != ConsoleKey.Escape)
                            processKey = Console.ReadKey(true);

                        if (processKey.Key == ConsoleKey.Enter)
                        {
                            Console.WriteLine("Exited the current game.");
                            Console.WriteLine();
                            break;
                        }
                        else
                        {
                            Console.WriteLine("You are continuing the game. Type an integer.");
                            Console.WriteLine();
                            continue;
                        }
                    }
                    else if (currentChar.Key == ConsoleKey.Enter)
                    {
                        //Enter button is pushed and the input is evaluated.

                        Console.WriteLine();                        

                        if (int.TryParse(betString, out int bet) && bet > 0 && bet < 100)
                        {
                            // Input is a proper number. 

                            // Codes here increments the trial count first.
                            // Then checks if the number is guessed correctly and finishes the game if so. 
                            // Then evaluates the trial count and finishes the game if it is 10.
                            // Then guides the user according to the input number.

                            trials++; // The trial count is incremented.

                            if (bet == correctNum)   // Number is guessed correctly.
                            {
                                ChangeColor("Congratulations! You guessed the number correctly.", true);
                                Console.WriteLine();
                                Console.WriteLine($"Your trial count: {trials}");
                                break;
                            }

                            else if (trials == 10)   // The number isn't guessed and no more trials left. 
                            {
                                ChangeColor("You couldn't guess the number correctly in 10 trials."); 
                                Console.WriteLine();
                                break;
                            }
                            else if (bet > correctNum)   // Bet is bigger than the correct number.
                                ChangeColor("Type a smaller number. ");                           
                            else   // Bet is smaller than the correct number.
                                ChangeColor("Type a bigger number. ");

                            Console.Write("Trial count: ");
                            if (trials >= 8)   // Makes the trial count red if 3 or less trials are left. 
                                ChangeColor(trials.ToString());
                            else
                                Console.Write(trials);
                            Console.WriteLine();
                        }
                        else // Input is not a proper number.
                            Console.WriteLine("You didn't provide a proper number.");

                        betString = ""; // Resets the bet string.
                        Console.WriteLine();
                    }
                    else if (currentChar.Key == ConsoleKey.Backspace)
                    {
                        // Backspace button is pushed.

                        if (betString.Length != 0) 
                        {
                            // Deletes a character from the end of the line if the line is not empty.
                            betString = betString.Remove(betString.Length - 1);
                            Console.Write("\b \b");
                        }
                        
                        // Does nothing and continues if the line is empty.
                    }
                    else
                    {
                        // Adds the provided character to the bet string.
                        betString += currentChar.KeyChar;
                        Console.Write(currentChar.KeyChar);
                    }
                }
            }
            else
            {
                // User quits the game.
                Console.WriteLine("You exited the game.");
                break;
            }
        }
    }
}
